services:

  mongo:
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    command: ["--noauth"]
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: admin
    #   MONGO_INITDB_ROOT_PASSWORD: 123456
